### PR TITLE
WIP: Use standardized way to run the application 

### PR DESCRIPTION
**Pull request by tomkukral**
This PR introduces env with 2 containers (nginx and php-fpm) and suggest changins application root to **/**.

Howerver it is not suitable for foreign developers since it uses *registry.in.fit.cvut.cz:443/ict/nginx-symfony* image from your **private** repository. This can be legitimate reason to close the PR.

**vhost.conf** file used in _ict/nginx-symfony_:
```
server {
	listen 80;

	server_name _;

	root /var/www/html/web/;

	index app.php;


	location / {
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $http_host;

		fastcgi_pass app:9000;
		include fastcgi_params;

		fastcgi_param SCRIPT_FILENAME $document_root/app.php;
	}

	location ~ /(bundles|images) {
		root /var/www/html/web/;
		access_log off;
		expires 7d;
		disable_symlinks off;
	}
}
```

### CODE REVIEW

**Comment by tomaskadlec** [comment]
I do not consider private images as the biggest problem here. I see a much more important issue here. How to _build_ `web` directory. There are `app.php` and its variants for different environments and static assets. The assets are copied/linked from bundles or worse they are assembled by some  other tool (e.g. assetic, bower). It should be clear how this works in dev environment (changes in assets should be propagated immediately), prod environment (assets should be assembled only once when application starts). Other environments (as test or custom) should be considered also.

**Comment by tomkukral** [comment]
Image from private repository is a big blocker for somebody trying run application without access to _registry.in.fit._ This PR **overrides** previous Dockerfile and effectivelly make it imposible to use `docker-compose` for development.

_Dockerfile_ defines how to build an *app* container and _docker-compose.yml_ gives container assembling instructions. It works in current state of an application and does not try to address any future requirements.

**Comment by tomkukral** [comment]
Please hold this PR, I'm going to improve it and make it usable for devs.

**Comment by tomkukral** [comment]
I have added configuration for nginx image and thus it doest not break #9 and `docker-compose up` works.

RFC

**Comment by tomkukral** [comment]
Closing stale PR

**Pull request closed without merging**
